//Find
		enum
		{
			MBS_CLICK,
			MBS_PRESS,
		};
		
///Add
#if defined(ENABLE_PARTY_MATCH)
		enum
		{
			PARTY_MATCH_SEARCH,
			PARTY_MATCH_CANCEL,
			PARTY_MATCH_REQUIRED_ITEM_MAX = 3,
			//
			PARTY_MATCH_INFO = PARTY_MATCH_SEARCH,
			PARTY_MATCH_FAIL,
			PARTY_MATCH_SUCCESS,
			PARTY_MATCH_START,
			PARTY_MATCH_CANCEL_SUCCESS,
			PARTY_MATCH_FAIL_NO_ITEM,
			PARTY_MATCH_FAIL_LEVEL,
			PARTY_MATCH_FAIL_NOT_LEADER,
			PARTY_MATCH_FAIL_MEMBER_NOT_CONDITION,
			PARTY_MATCH_FAIL_NONE_MAP_INDEX,
			PARTY_MATCH_FAIL_IMPOSSIBLE_MAP,
			PARTY_MATCH_HOLD,
			PARTY_MATCH_FAIL_FULL_MEMBER,

		};
#endif